spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stadiumfind
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token-expiration: 86400000 # 24 giờ (ms)
  refresh-token-expiration: 604800000 # 7 ngày (ms)